### PR TITLE
ANA-4466: remove dead key

### PR DESCRIPTION
**Pull request by sBond-finbourne**
# Pull Request Checklist

- [x] Read the [contributing guidelines](../blob/master/docs/CONTRIBUTING.md)
- [ ] Tests pass
- [ ] Raised the PR against the `develop` branch

# Description of the PR

Describe the code changes for the reviewers, explain the solution you have provided and how it fixes the issue

### CODE REVIEW

**Review by TomCrawleyFBN — APPROVED** [review]
LGTM

**Review by cplaverty — APPROVED** [review]
/LGTM

**Review by Matt-Storey-Finbourne — APPROVED** [review]

**Pull request merged**
